Improve tests for project script's folder
The project_scripts_dir_name must not start with numbers and this test is not passing yet.
The project_dir_name can start with number but the project_scripts_dir_name not.
It could cause SyntaxError as shown below

>>> from 1test_py import main
  File "<stdin>", line 1
    from 1test_py import main
         ^
SyntaxError: invalid decimal literal

See #5
See #9
See #13